services:
  nginx:
    build:
      dockerfile: dockerfile.nginx
    container_name: nginx
    restart: unless-stopped
    ports: 
      - "80:80"

  postgresql:
    build:
      dockerfile: dockerfile.postgres
    container_name: postgresql
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=tr_ibd_owner
      - POSTGRES_PASSWORD=owner_pass
      - POSTGRES_DB=tr_ibd

  postgrest:
    image: postgrest/postgrest
    container_name: postgrest
    restart: unless-stopped
    ports: 
      - "3000:3000"
    environment:
      - PGRST_DB_URI=postgres://tr_ibd_owner:owner_pass@host.docker.internal/tr_ibd
      - PGRST_DB_SCHEMA=public
      - PGRST_DB_ANON_ROLE=tr_ibd_owner
      - PGRST_JWT_SECRET=abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz
      - PGRST_DB_PRE_REQUEST=set_timeout_fn