create role tr_ibd_esfm nologin;
-- ALTER ROLE tr_ibd_esfm SET statement_timeout = 10000;

create role tr_ibd_ocn nologin;
-- ALTER ROLE tr_ibd_ocn SET statement_timeout = 3000;

CREATE TABLE public.films (
    code        char(5) CONSTRAINT firstkey PRIMARY KEY,
    title       varchar(40) NOT NULL,
    did         integer NOT NULL,
    date_prod   date,
    kind        varchar(10),
    len         interval hour to minute
);

CREATE TABLE public.distributors (
     did    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     name   varchar(40) NOT NULL CHECK (name <> '')
);

insert into public.films (code, title, did, date_prod, kind, len) values ('tnj', 'Tom and Jerry', 1, '1981-01-01', 'mult', '1 hours 20 minutes');
	
insert into public.films (code, title, did, date_prod, kind, len) values ('sup', 'Superman', 1, '1991-01-01', 'film', '2 hours 10 minutes');

insert into public.distributors (did, name) values (1, 'Paramount');
	
insert into public.distributors (did, name) values (2, '20 Century Fox');

create view public.films_vw as select * from films;

grant select on public.films_vw to tr_ibd_esfm;

create view public.distributors_vw as select * from distributors;

grant select on public.distributors_vw to tr_ibd_ocn;
grant insert on public.distributors to tr_ibd_ocn;

CREATE OR REPLACE FUNCTION public.delay_fn()
RETURNS VOID AS $$
BEGIN
	PERFORM pg_sleep(5);
END;
$$
LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.set_timeout_fn()
RETURNS VOID AS $$
BEGIN
	SET statement_timeout = 3000;
END;
$$
LANGUAGE plpgsql;

grant execute on function public.delay_fn() to tr_ibd_ocn;
grant execute on function public.delay_fn() to tr_ibd_esfm;

create schema postgrest;
grant usage on schema postgrest to tr_ibd_owner;

create schema test;
grant usage on schema test to tr_ibd_owner;
GRANT USAGE ON SCHEMA test TO tr_ibd_esfm;
GRANT USAGE ON SCHEMA test TO tr_ibd_ocn;

create view test.test_films_vw as select * from films;

GRANT SELECT ON TABLE test.test_films_vw TO tr_ibd_esfm;
GRANT SELECT ON TABLE test.test_films_vw TO tr_ibd_ocn;

create or replace function postgrest.pre_config_fn()
returns void as $$
  select
      set_config('pgrst.db_schemas', 'public, test', true)
    , set_config('pgrst.db_pre_request', 'set_timeout_fn', true)
    , set_config('pgrst.db_anon_role', 'tr_ibd_owner', true)
    , set_config('pgrst.server_timing_enabled', 'true', true);
$$ language sql;
